name: TVBOX_Sync

on:
  push:
    branches:
      -master
  schedule:
    - cron: 0 */24 * * *
    # 每隔12小时
  workflow_dispatch:
jobs:
  update_tvbox_fongmi_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: FongMi/TV  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: fongmi  # 默认推送到你的仓库master分支
          force: false  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_live_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: haha459862/TVboxOSC  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: live  # 默认推送到你的仓库master分支
          force: false  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_win_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: q215613905/TVBoxOS  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: win  # 默认推送到你的仓库master分支
          force: false  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_takagen_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: takagen99/Box  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: takagen99  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_kensonmiao_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: kensonmiao/CatVodTVOSC  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: kensonmiao  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_Pyramid_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: UndCover/Pyramid  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: Pyramid  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
