name: TVBOX_Sync

on:
  push:
    branches:
      -master
  schedule:
    - cron: 0 */12 * * *
    # 每隔12小时
  workflow_dispatch:
jobs:
  update_tvbox_main_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: CatVodTVOfficial/TVBoxOSC  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: main  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_dev_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: CatVodTVOfficial/TVBoxOSC  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: dev  # 默认是拉取上游仓库的master分支
          target_branch: dev  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_live_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: haha459862/TVboxOSC  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: live  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
  update_tvbox_win_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: q215613905/TVBoxOS  # 上游仓库
          target_repository: sxx1314/CatVodTVOSC  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: win  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
